name: "CI"
on:
    push:
        branches:
        - master
    pull_request:
        types: [opened, synchronize]
    workflow_dispatch:

concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:  
    build:
        name: "Test"
        runs-on: ${{ 
            (matrix.os == 'linux')   && (matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest') ||
            (matrix.os == 'macos')   && (matrix.arch == 'arm64' && 'macos-latest' || 'macOS-15-intel') ||
            (matrix.os == 'windows') && 'windows-latest' || 
                                        'ubuntu-latest'  }}
        strategy:
            fail-fast: false
            matrix:
                include: 
                    - {os: linux,   arch: amd64}
                    - {os: linux,   arch: arm64}
                    # - {os: freebsd, arch: amd64}
                    - {os: macos,   arch: amd64}
                    - {os: macos,   arch: arm64}
                    - {os: windows, arch: amd64}
                    
        defaults:
            run:
                shell: ${{ 
                    (matrix.os == 'freebsd') && 'freebsd {0}' ||
                    (matrix.os == 'windows') && 'msys2 {0}'   || 
                                                'bash'        }}

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4
              with:
                submodules: recursive

            - name: Setup Arturo
              uses: arturo-lang/setup-arturo@v2
              with: 
                token: ${{ secrets.GITHUB_TOKEN }}
                os: ${{ matrix.os }}
                arch: ${{ matrix.arch }}

            - name: Run unit tests
              run: |
                cd $GITHUB_WORKSPACE
                arturo -e "inspect sys\deps"
                arturo tests/test1.art